// Code generated by schemagen; DO NOT EDIT

package document

const (
	DocCustomerBirthDate                       = "$.customer.birth_date"
	DocCustomerName                            = "$.customer.name"
	DocCustomerNik                             = "$.customer.nik"
	DocId                                      = "$.id"
	DocProcessAgeCheckPassed                   = "$.process.age_check_passed"
	DocProcessAssetCondition                   = "$.process.asset.condition"
	DocProcessAssetLicensePlate                = "$.process.asset.license_plate"
	DocProcessDuplicatePlateCheckPassed        = "$.process.duplicate_plate_check_passed"
	DocProcessFinalReviewConfirmed             = "$.process.final_review.confirmed"
	DocProcessIncomeVerifiedAmount             = "$.process.income.verified_amount"
	DocProcessLoanStructureLtvMax              = "$.process.loan_structure.ltv_max"
	DocProcessLoanStructureLtvSubmission       = "$.process.loan_structure.ltv_submission"
	DocProcessLoanStructureMaxFunding          = "$.process.loan_structure.max_funding"
	DocProcessLoanStructureProvisionalAmount   = "$.process.loan_structure.provisional_amount"
	DocProcessScoringCalculationEffectiveLtv   = "$.process.scoring.calculation.effective_ltv"
	DocProcessScoringCalculationMaxFunding     = "$.process.scoring.calculation.max_funding"
	DocProcessScoringRiskSystemMaxLtv          = "$.process.scoring.risk_system.max_ltv"
	DocProcessScoringRiskSystemRejectReason    = "$.process.scoring.risk_system.reject_reason"
	DocProcessScoringRiskSystemRequestId       = "$.process.scoring.risk_system.request_id"
	DocProcessScoringRiskSystemRequiredDataSet = "$.process.scoring.risk_system.required_data_set"
	DocProcessScoringRiskSystemRiskType        = "$.process.scoring.risk_system.risk_type"
	DocProcessScoringRiskSystemScoredAt        = "$.process.scoring.risk_system.scored_at"
	DocProcessScoringRiskSystemStatus          = "$.process.scoring.risk_system.status"
	DocProcessScoringStageToken                = "$.process.scoring.stage_token"
	DocProcessScoringSurveyType                = "$.process.scoring.survey_type"
	DocProcessScoringTriggerSeq                = "$.process.scoring.trigger_seq"
	DocProcessStatusTimestampsApproved         = "$.process.status_timestamps.approved"
	DocProcessStatusTimestampsNew              = "$.process.status_timestamps.new"
	DocProcessStatusTimestampsProcessing       = "$.process.status_timestamps.processing"
	DocProcessStatusTimestampsRejected         = "$.process.status_timestamps.rejected"
	DocProcessStatusTimestampsTerminal         = "$.process.status_timestamps.terminal"
	DocStatus                                  = "$.status"
	DocStatusReason                            = "$.status_reason"
	DocSubmissionDate                          = "$.submission_date"
)

type DocTypeCustomerBirthDate = string
type DocTypeCustomerName = string
type DocTypeCustomerNik = string
type DocTypeId = string
type DocTypeProcessAgeCheckPassed = bool
type DocTypeProcessAssetCondition = string
type DocTypeProcessAssetLicensePlate = string
type DocTypeProcessDuplicatePlateCheckPassed = bool
type DocTypeProcessFinalReviewConfirmed = bool
type DocTypeProcessIncomeVerifiedAmount = float64
type DocTypeProcessLoanStructureLtvMax = float64
type DocTypeProcessLoanStructureLtvSubmission = float64
type DocTypeProcessLoanStructureMaxFunding = float64
type DocTypeProcessLoanStructureProvisionalAmount = float64
type DocTypeProcessScoringCalculationEffectiveLtv = float64
type DocTypeProcessScoringCalculationMaxFunding = float64
type DocTypeProcessScoringRiskSystemMaxLtv = float64
type DocTypeProcessScoringRiskSystemRejectReason = string
type DocTypeProcessScoringRiskSystemRequestId = string
type DocTypeProcessScoringRiskSystemRequiredDataSet = string
type DocTypeProcessScoringRiskSystemRiskType = string
type DocTypeProcessScoringRiskSystemScoredAt = string
type DocTypeProcessScoringRiskSystemStatus = string
type DocTypeProcessScoringStageToken = string
type DocTypeProcessScoringSurveyType = string
type DocTypeProcessScoringTriggerSeq = int
type DocTypeProcessStatusTimestampsApproved = string
type DocTypeProcessStatusTimestampsNew = string
type DocTypeProcessStatusTimestampsProcessing = string
type DocTypeProcessStatusTimestampsRejected = string
type DocTypeProcessStatusTimestampsTerminal = string
type DocTypeStatus = string
type DocTypeStatusReason = string
type DocTypeSubmissionDate = string
